version: '3.8'

services:
   db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_DATABASE: '${MYSQL_DB_NAME}'
      MYSQL_USER: '${MYSQL_USERNAME}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
    ports:
      - "${MYSQL_DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app
    hostname: db
   server:
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - "4000:${PORT}"
    depends_on:
      - db
    networks:
      - app

volumes:
  mysql_data:

networks:
  app:


